name: Build SIF for BaseJ

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t basej-custom:latest container/
          docker save basej-custom:latest -o basej-custom.tar

      - name: Install Apptainer
        uses: eWaterCycle/setup-apptainer@v2

      - name: Convert to SIF
        run: |
          apptainer build basej-custom.sif docker-archive://basej-custom.tar

      - name: Upload SIF
        uses: actions/upload-artifact@v4
        with:
          name: basej-dnaqc-custom-sif
          path: basej-custom.sif
