name: Build SIF for BaseJ

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Locate and Build Docker Image
        run: |
          TARGET_DOCKERFILE=$(find . -iname "*dockerfile*" | head -n 1)
          CONTEXT_DIR=$(dirname "$TARGET_DOCKERFILE")
          docker build -t basej-custom:latest -f "$TARGET_DOCKERFILE" "$CONTEXT_DIR"
          docker save basej-custom:latest -o basej-custom.tar

      - name: Install Apptainer
        uses: eWaterCycle/setup-apptainer@v2

      - name: Convert to SIF
        run: |
          apptainer build basej-custom.sif docker-archive://basej-custom.tar

      - name: Release SIF file
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.0
          name: BaseJ Custom SIF
          files: basej-custom.sif
